import banner from 'rollup-plugin-banner';
import commonjs from 'rollup-plugin-commonjs';
import resolve from 'rollup-plugin-node-resolve';
import typescript from 'rollup-plugin-typescript';

const bannerText = [
    'BudapestGo',
    '<%= pkg.description %>',
    '',
    'Version <%= pkg.version %>',
    'By <%= pkg.author %>',
    '',
    'License <%= pkg.license %>',
    '',
    'This is an autogenerated file. DO NOT EDIT!',
].join('\n');

export default [
    {
        input: './src/MMM-budapest-go.ts',
        plugins: [
            typescript(),
            resolve(),
            commonjs(),
            banner(bannerText),
        ],
        output: {
            file: './MMM-budapest-go.js',
            format: 'iife',
        },
    }, {
        input: './src/node_helper.ts',
        plugins: [
            typescript(),
            banner(bannerText),
        ],
        output: {
            file: './node_helper.js',
            format: 'umd',
        },
    },
]
